# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  name: "lightning_v0.1" # RUN NAME
  save_dir: "${paths.output_dir}"
  offline: True
  id: null # pass correct id to resume experiment!
  anonymous: null # enable anonymous logging
  project: "unpaired_g2b_single_A40" # PROJECT NAME
  log_model: False # upload lightning ckpts
  prefix: "" # a string to put at the beginning of metric keys
  # entity: "" # set to name of your wandb team
  group: ""
  tags: []
  job_type: ""
